
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  branch = "master"
  name = "github.com/blevesearch/bleve"

[[constraint]]
  branch = "master"
  name = "github.com/boltdb/bolt"

[[constraint]]
  branch = "master"
  name = "github.com/drhodes/golorem"

[[constraint]]
  branch = "master"
  name = "github.com/elazarl/go-bindata-assetfs"

[[constraint]]
  name = "github.com/gtank/cryptopasta"

[[constraint]]
  branch = "master"
  name = "github.com/julienschmidt/httprouter"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  branch = "master"
  name = "github.com/pkg/errors"

[[constraint]]
  branch = "master"
  name = "github.com/sirupsen/logrus"

[[constraint]]
  name = "github.com/spf13/cobra"

[[constraint]]
  name = "github.com/spf13/viper"

[[constraint]]
  branch = "master"
  name = "github.com/stretchr/testify"

[[constraint]]
  branch = "master"
  name = "github.com/twinj/uuid"

[[constraint]]
  name = "golang.org/x/net"
